# Generated by Django 4.1.1 on 2022-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roof_age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('monthly_bill', models.IntegerField()),
                ('HOA', models.BooleanField(default=True)),
                ('battery', models.BooleanField(default=True)),
                ('foundation', models.BooleanField(default=True)),
                ('roof_type', models.CharField(max_length=20)),
                ('availability', models.DateTimeField()),
                ('bill', models.FileField(upload_to='uploads/%d/%m/%y/')),
            ],
        ),
    ]
