# Generated by Django 4.1.1 on 2022-09-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'details', 'verbose_name_plural': 'details'},
        ),
    ]
