# Generated by Django 4.1.1 on 2022-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0004_alter_details_hoa_alter_details_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='HOA',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='battery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='foundation',
            field=models.BooleanField(default=True),
        ),
    ]
