# Generated by Django 4.1.1 on 2022-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0005_alter_details_hoa_alter_details_battery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roof_age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('monthly_bill', models.IntegerField()),
                ('HOA', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('battery', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('foundation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('roof_type', models.CharField(choices=[('Comp Shingle', 'Comp Shingle'), ('Concrete', 'Concrete'), ('Metal', 'Metal'), ('Spanish', 'Spanish'), ('Clay', 'Clay'), ('Other', 'Other')], default='Comp Shingle', max_length=20)),
                ('availability', models.DateTimeField()),
                ('bill', models.FileField(upload_to='uploads/%d/%m/%y/')),
            ],
            options={
                'verbose_name': 'details',
                'verbose_name_plural': 'details',
            },
        ),
    ]
