# Generated by Django 4.1.1 on 2022-10-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0006_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Register',
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'register', 'verbose_name_plural': 'register'},
        ),
    ]
