# Generated by Django 4.1.1 on 2022-11-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0007_rename_detail_register_alter_register_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='questions',
            field=models.CharField(default='No questions', max_length=800),
        ),
    ]
