# Generated by Django 4.1.1 on 2022-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0008_register_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='company_name',
            field=models.CharField(default='SolarCity', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='meter_picture',
            field=models.FileField(default='null.jpg', upload_to='uploads/%d/%m/%y/'),
        ),
    ]
