# Generated by Django 4.1.1 on 2022-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskin', '0009_register_company_name_register_meter_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='meter_picture',
            field=models.FileField(upload_to='uploads/%d/%m/%y/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='questions',
            field=models.CharField(max_length=800),
        ),
    ]
