name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into DigitalOcean droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: 1@Nishant
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p backups
          ls
    - name: Copy code to DigitalOcean droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: 1@Nishant
        source: .
        target: /var/www/project/BaskinSolar
    - name: Execute scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: 1@Nishant
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/project 
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          deactivate
          cd BaskinSolar
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          sudo ufw delete allow 8000
          sudo ufw allow 'Nginx Full'
