name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into DigitalOcean droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: 1@Nishant
        key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Backup old artifacts
      run: |
        mkdir -p backups
        mv /var/www/project/BaskinSolar /var/www/project/BaskinSolar.bak$(date +%Y%m%d%H%M%S)
    - name: Copy code to DigitalOcean droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: .
        target: /var/www/project
    - name: Create VEM
      run: |
        cd /var/www/project 
        python3 -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        deactivate
    - name: Build everything
      run: |
        cd BaskinSolar
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic
    - name: Restart web server
      run: |
        sudo systemctl daemon-reload
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        sudo ufw delete allow 8000
        sudo ufw allow 'Nginx Full'
